spring:
  datasource:
    url:
      jdbc:postgresql://localhost:5432/qrcompany
    username: postgres
    password: qwerty12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update